# use this to iterate on changes to config without rebuilding the entire
# image from scratch; ensure to clean the right stamps/folders to correctly
# trigger rebuild with Buildroot

ARG BASE_VERSION=latest

# named target with generated machine identity SSH key
FROM unframework/licheepi-nano-buildroot:$BASE_VERSION AS localsshkey
WORKDIR /root/licheepi-nano
RUN ssh-keygen -b 4096 -t rsa -f root_id_rsa -N '' -C 'root@LicheePiNano'

# main build target
FROM unframework/licheepi-nano-buildroot:$BASE_VERSION AS local

# copy newest version of local files
WORKDIR /root/licheepi-nano
COPY board/ board/
COPY configs/ configs/
COPY \
    Config.in \
    external.desc \
    external.mk \
    ./

# embed generated machine identity SSH key
# (the .ssh chmod runs in a post-image script)
COPY --from=localsshkey /root/licheepi-nano/root_id_rsa board/licheepi_nano/rootfs-overlay/root/.ssh/id_rsa

# reset Buildroot config and trigger Linux kernel rebuild
WORKDIR /root/buildroot
RUN BR2_EXTERNAL=/root/licheepi-nano make licheepi_nano_defconfig
RUN cd output/build/uboot-v2021.01-f1c100s-4/ && rm .stamp_built .stamp_*installed
RUN cd output/build/host-uboot-tools-2021.07/ && rm .stamp_built .stamp_*installed
RUN cd output/build/linux-custom/ && rm .stamp_dotconfig .stamp_configured .stamp_built .stamp_*installed
RUN cd output/build/linux-firmware-20221214/ && rm .stamp_built .stamp_*installed

# re-run build
RUN make

# expose built image files in standalone root folder
FROM scratch AS localout
COPY --from=local /root/buildroot/output/images/ .
